name: lobe-chat-database
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    volumes:
      - 'chatdb_data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=$SERVICE_USER_POSTGRESSQL'
      - 'POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRESSQL'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    volumes:
      - 's3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${SERVICE_USER_MINIO}'
      - 'MINIO_ROOT_PASSWORD=${SERVICE_PASSWORD_MINIO}'
      - 'MINIO_DOMAIN=${SERVICE_FQDN_API}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https:${APP_URL}' # Your LobeChat's domain name.
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"


  logto:
    image: svhd/logto
    container_name: lobe-logto
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL='postgresql://'.'${SERVICE_USER_POSTGRESSQL}:'.'${SERVICE_PASSWORD_POSTGRESSQL}'.'@postgresql:5432/logto''
      - 'ENDPOINT=${SERVICE_FQDN_ENDPOINT}'
      - 'ADMIN_ENDPOINT=${SERVICE_FQDN_ADMIN}'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-chat
    depends_on:
      - postgresql
      - minio
      - logto
    env_file:
      - .env
