name: lobe-chat-database
services:
  postgresql:
    image: 'pgvector/pgvector:pg16'
    volumes:
      - 'chatdb_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=lobe
      - POSTGRES_PASSWORD=uWNZugjBqixf8dxC
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres'
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    volumes:
      - 's3_data:/etc/minio/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=uWNZugjBqixf8dxC
      - MINIO_DOMAIN=https://s3api.spidmax.com
      - 'MINIO_API_CORS_ALLOW_ORIGIN=https:${APP_URL}'
    restart: always
    command: "server /etc/minio/data --address \":9000\" --console-address \":9001\"\n"
  logto:
    image: svhd/logto
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto'
      - TRUST_PROXY_HEADER=1
      - ENDPOINT=https://logto-api.spidmax.com
      - ADMIN_ENDPOINT=https://logto.spidmax.com
    entrypoint:
      - sh
      - '-c'
      - 'npm run cli db seed -- --swe && npm start'
  lobe:
    image: lobehub/lobe-chat-database
    depends_on:
      - postgresql
      - minio
      - logto
    env_file:
      - .env
